name: Run integration tests
on: [pull_request]

env:
  POSTGRESQL_HOST: ${{ vars.POSTGRESQL_HOST }}
  POSTGRESQL_USER: ${{ secrets.POSTGRESQL_USER }}
  POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}
  POSTGRESQL_DB: ${{ vars.POSTGRESQL_DB }}
  PORT: ${{ vars.PORT }}

jobs:
  # Label of the container job
  run-tests:
    
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4  

      - name: Install postgres
        run: |
          sudo apt-get update
          sudo apt-get install postgresql postgresql-contrib
          sudo service postgresql start
          sudo -u postgres psql -c "CREATE DATABASE ${{vars.POSTGRESQL_DB}};"
          sudo -u postgres psql -c "CREATE USER ${{secrets.POSTGRESQL_USER}} WITH PASSWORD '${{secrets.POSTGRESQL_PASSWORD}}';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${{vars.POSTGRESQL_DB}} TO ${{secrets.POSTGRESQL_USER}};"
        
      

      - name: Install dependencies
        run: npm install

      - name: Run server
        run: node server.js &
      
      - name: Run tests
        run: npm test
