name: Run integration tests
on: [pull_request]

jobs:
  # Label of the container job
  run-tests:
    
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4  

      - name: Install postgres
        run: |
          sudo apt-get update
          sudo apt-get install postgresql postgresql-contrib
          sudo service postgresql start
          sudo -u postgres psql -c "CREATE USER postgres WITH PASSWORD '${{secrets.POSTGRESQL_PASSWORD}}';"

      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test
        env:
          POSTGRESQL_HOST: ${{ env.POSTGRESQL_HOST }}
          POSTGRESQL_USER: ${{ secrets.POSTGRESQL_USER }}
          POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}
          POSTGRESQL_DB: ${{ env.POSTGRESQL_DB }}
          PORT: ${{ env.PORT }}
